### ISSUE TITLE
Things lacking after setup

### ISSUE THREAD

**Issue by pepegar** [frees-io/freestyle-http#3]
- [x] Codecov setup
- [x] Travis is setup, but need to check if integration works correctly (part done in #1, being finished in #5)
- ~Fix badges at the top of the README~ (`sbt-org-policies` will do the work here)

**Comment by juanpedromoreno** [comment]
See https://github.com/frees-io/freestyle-http/pull/1

**Comment by juanpedromoreno** [comment]
I think everything is already fixed 👍  . Feel free to close the issue if you agree.

**Comment by pepegar** [comment]
👍  fixed indeed!
